services:
    cache_control_manager:
        class: \PoP\CacheControl\Managers\CacheControlManager
        public: true

    PoP\CacheControl\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true
