services:
    cache_control_engine:
        class: \PoP\CacheControl\Managers\CacheControlEngine
        public: true

    cache_control_manager:
        class: \PoP\CacheControl\Managers\CacheControlManager
        public: true

    PoP\CacheControl\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true

    PoP\CacheControl\TypeResolverDecorators\:
        resource: '../src/TypeResolverDecorators/*'
        public: true
