services:
    cache_control_engine:
        class: \PoP\CacheControl\Managers\CacheControlEngine
        public: true

    PoP\CacheControl\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true
